### ISSUE TITLE
Public chat roadmap

### ISSUE THREAD

**Issue by jjalonso** [jjalonso/codename-chatita#25]
- [ ] Design journey to start an anonymous chat session

- [ ] Build UI for the journey

- [ ] Fix connection errors to use useChannel hook from public

- [ ] Build seller payment setup

- [ ] Build customer payment flow
